## Exercise 6: Choosing the best performing model on a dataset

Instructions:

- Use the Dataset File to train your model
- Use the Test File to generate your results
- Use the Sample Submission file to generate the same format
- Use all Regression models

Submit your results to:
https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques/overview

In [1]:
import pandas as pd
import seaborn as sns

from matplotlib import pyplot as plt
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

## Dataset File

In [2]:
train_data = 'https://github.com/robitussin/CCMACLRL_EXERCISES/blob/3fd7d51ffd17863598ac3f44eeefc558171a5b73/dataset/house-prices-advanced-regression-techniques/train.csv?raw=true'
df = pd.read_csv(train_data)

In [3]:
# inspect first data
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
# inspect last data
df.tail()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

# Removing null value

In [6]:
df_output = df.isnull().sum().sort_values(ascending=False)
display(df_output)

PoolQC           1453
MiscFeature      1406
Alley            1369
Fence            1179
MasVnrType        872
                 ...
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice           0
Length: 81, dtype: int64

In [7]:
cols_to_drop = df.isnull().sum()[df.isnull().sum() > 1000].index.tolist()

df_cleaned = df.drop(columns=cols_to_drop)

print(f"Original number of columns: {df.shape[1]}")
print(f"Number of columns after dropping: {df_cleaned.shape[1]}")
display(df_cleaned.head())

Original number of columns: 81
Number of columns after dropping: 77

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [8]:
missing_values_cleaned = df_cleaned.isnull().sum().sort_values(ascending=False)
display(missing_values_cleaned[missing_values_cleaned > 0])

MasVnrType      872
FireplaceQu     690
LotFrontage     259
GarageFinish     81
GarageQual       81
GarageCond       81
GarageType       81
GarageYrBlt      81
BsmtExposure     38
BsmtFinType2     38
BsmtCond         37
BsmtFinType1     37
BsmtQual         37
MasVnrArea        8
Electrical        1
dtype: int64

# Encoding for string data

In [9]:
# checl categorical columns with missing values
categorical_cols_with_missing = df_cleaned.select_dtypes(include='object').columns[df_cleaned.select_dtypes(include='object').isnull().any()]

# impute missing values with mode
for col in categorical_cols_with_missing:
    mode_val = df_cleaned[col].mode()[0]
    df_cleaned[col].fillna(mode_val, inplace=True)

# check missing values after impute
print("check missing values after impute:")
display(df_cleaned[categorical_cols_with_missing].isnull().sum())

# one hot encoding on all object
df_encoded = pd.get_dummies(df_cleaned, columns=df_cleaned.select_dtypes(include='object').columns, dummy_na=False)

print()
print("after one-hot encoding:")
print(df_encoded.shape)
display(df_encoded.head())
display(df_encoded.tail())

check missing values after impute:

/tmp/ipython-input-1075201274.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned[col].fillna(mode_val, inplace=True)

MasVnrType      0
BsmtQual        0
BsmtCond        0
BsmtExposure    0
BsmtFinType1    0
BsmtFinType2    0
Electrical      0
FireplaceQu     0
GarageType      0
GarageFinish    0
GarageQual      0
GarageCond      0
dtype: int64

after one-hot encoding:
(1460, 276)

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,False,False,False,True,False,False,False,False,True,False
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,False,False,False,True,False,False,False,False,True,False
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,False,False,False,True,False,False,False,False,True,False
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,False,False,False,True,True,False,False,False,False,False
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,False,False,False,True,False,False,False,False,True,False

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,...,False,False,False,True,False,False,False,False,True,False
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,...,False,False,False,True,False,False,False,False,True,False
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,...,False,False,False,True,False,False,False,False,True,False
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,...,False,False,False,True,False,False,False,False,True,False
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,...,False,False,False,True,False,False,False,False,True,False

## Test File

In [10]:
test_url = 'https://github.com/robitussin/CCMACLRL_EXERCISES/blob/3fd7d51ffd17863598ac3f44eeefc558171a5b73/dataset/house-prices-advanced-regression-techniques/test.csv?raw=true'
dt=pd.read_csv(test_url)

In [11]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1455 non-null   object
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   object
 6   Alley          107 non-null    object
 7   LotShape       1459 non-null   object
 8   LandContour    1459 non-null   object
 9   Utilities      1457 non-null   object
 10  LotConfig      1459 non-null   object
 11  LandSlope      1459 non-null   object
 12  Neighborhood   1459 non-null   object
 13  Condition1     1459 non-null   object
 14  Condition2     1459 non-null   object
 15  BldgType       1459 non-null   object
 16  HouseStyle     1459 non-null   object
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   object
 22  RoofMatl       1459 non-null   object
 23  Exterior1st    1458 non-null   object
 24  Exterior2nd    1458 non-null   object
 25  MasVnrType     565 non-null    object
 26  MasVnrArea     1444 non-null   float64
 27  ExterQual      1459 non-null   object
 28  ExterCond      1459 non-null   object
 29  Foundation     1459 non-null   object
 30  BsmtQual       1415 non-null   object
 31  BsmtCond       1414 non-null   object
 32  BsmtExposure   1415 non-null   object
 33  BsmtFinType1   1417 non-null   object
 34  BsmtFinSF1     1458 non-null   float64
 35  BsmtFinType2   1417 non-null   object
 36  BsmtFinSF2     1458 non-null   float64
 37  BsmtUnfSF      1458 non-null   float64
 38  TotalBsmtSF    1458 non-null   float64
 39  Heating        1459 non-null   object
 40  HeatingQC      1459 non-null   object
 41  CentralAir     1459 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1457 non-null   float64
 48  BsmtHalfBath   1457 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1458 non-null   object
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1457 non-null   object
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    729 non-null    object
 58  GarageType     1383 non-null   object
 59  GarageYrBlt    1381 non-null   float64
 60  GarageFinish   1381 non-null   object
 61  GarageCars     1458 non-null   float64
 62  GarageArea     1458 non-null   float64
 63  GarageQual     1381 non-null   object
 64  GarageCond     1381 non-null   object
 65  PavedDrive     1459 non-null   object
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         3 non-null      object
 73  Fence          290 non-null    object
 74  MiscFeature    51 non-null     object
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1458 non-null   object
 79  SaleCondition  1459 non-null   object
dtypes: float64(11), int64(26), object(43)
memory usage: 912.0+ KB

## Sample Submission File

In [12]:
sample_submission_url ='https://github.com/robitussin/CCMACLRL_EXERCISES/blob/3fd7d51ffd17863598ac3f44eeefc558171a5b73/dataset/house-prices-advanced-regression-techniques/sample_submission.csv?raw=true'

sf=pd.read_csv(sample_submission_url)

In [13]:
sf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id         1459 non-null   int64
 1   SalePrice  1459 non-null   float64
dtypes: float64(1), int64(1)
memory usage: 22.9 KB

# Training and Splitting of Data

In [58]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
from matplotlib import pyplot as plt

import warnings as wrn
wrn.filterwarnings('ignore')

In [29]:
X = df_encoded.drop('SalePrice', axis=1)
y = df_encoded['SalePrice']

X = X.drop('Id', axis=1)
# print("Shape of features (X):", X.shape)
# print("Shape of target variable (y):", y.shape)
# display(X.head())
# display(y.head())

In [30]:
display(X_train.isnull().sum()[X_train.isnull().sum() > 0])

Series([], dtype: int64)

In [31]:
numerical_cols_for_imputation = ['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

for col in numerical_cols_for_imputation:
    if col in df_encoded.columns:
        median_val = df_encoded[col].median()
        df_encoded[col].fillna(median_val, inplace=True)

print("missing values in numerical columns after imputation in df_encoded:")
display(df_encoded[numerical_cols_for_imputation].isnull().sum())

missing values in numerical columns after imputation in df_encoded:

/tmp/ipython-input-3945544883.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_encoded[col].fillna(median_val, inplace=True)

LotFrontage    0
MasVnrArea     0
GarageYrBlt    0
dtype: int64

In [36]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) # Using a common split ratio and random state

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (1022, 274)
Shape of X_test: (438, 274)
Shape of y_train: (1022,)
Shape of y_test: (438,)

## 1. Train a KNN Regressor

In [45]:
from sklearn.neighbors import KNeighborsRegressor

score_list = {}
KNN_regressor = KNeighborsRegressor(n_neighbors=7)
KNN_regressor.fit(X_train, y_train)
knn_score = KNN_regressor.score(X_test, y_test)

score_list["KNN Regressor"] = knn_score
print(f"Score is {knn_score}")

Score is 0.6365508154631163

- Perform cross validation

In [50]:
# put your answer here
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor(n_neighbors=5)
cv_scores = cross_val_score(knn, X_train, y_train, cv=5)

print('evaluation score',cv_scores)
print('average',cv_scores.mean())

if 'score_list' not in locals():
    score_list = {}
score_list["KNN Regressor (CV)"] = cv_scores.mean()

evaluation score [0.64069906 0.64042508 0.59718163 0.66332981 0.68231908]
average 0.6447909321976508

## 2. Train a SVM Regression

In [53]:
# put your answer here
from sklearn.svm import SVR

svc = SVR()
svc.fit(X_train, y_train)
svc_score = svc.score(X_test, y_test)

score_list["SVM"] = svc_score
print(f"Score is {svc_score}")

Score is -0.037705395447001244

- Perform cross validation

In [64]:
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVR

svm = SVR()

cv_scores_svm = cross_val_score(svm, X_train, y_train, cv=5)

print("cv scores", cv_scores_svm)
print("Average cv score:", cv_scores_svm.mean())

if 'score_list' not in locals():
    score_list = {}
score_list["SVM Regressor (CV)"] = cv_scores_svm.mean()

cv scores [-0.04470627 -0.06559437 -0.05180748 -0.0730947  -0.03562237]
Average cv score: -0.05416504015492492

## 3. Train a Decision Tree Regression

In [65]:
# put your answer here

from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=1)
dtc.fit(X_train,y_train)

dtc_score = dtc.score(X_test,y_test)
score_list["DTC"] = dtc_score
print(f"Score is {dtc_score}")

Score is 0.00228310502283105

- Perform cross validation

In [67]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeRegressor

# Initialize the Decision Tree Regressor model
dt_regressor = DecisionTreeRegressor(random_state=1) # Using a random state for reproducibility

# Perform 5-fold cross-validation
cv_scores_dt = cross_val_score(dt_regressor, X_train, y_train, cv=5)

print("cv scores", cv_scores_dt)
print("Average cv score", cv_scores_dt.mean())

if 'score_list' not in locals():
    score_list = {}
score_list["Decision Tree Regressor (CV)"] = cv_scores_dt.mean()

cv scores [0.24553566 0.63483072 0.66012192 0.7052338  0.82749125]
Average cv score 0.6146426711672254

## 4. Train a Random Forest Regression

In [75]:
from sklearn.ensemble import RandomForestRegressor

rfr = RandomForestRegressor(n_estimators=50, random_state=1)
rfr.fit(X_train, y_train)

rfr_score = rfr.score(X_test, y_test)

if not isinstance(score_list, dict):
    score_list = dict(score_list)

score_list["Random Forest Regressor"] = rfr_score
print(f"Score is {rfr_score}")

Score is 0.8944100698447502

## 5. Compare all the performance of all regression models

In [79]:
for alg,score in score_list:
    print(f"{alg} Score is {str(score)[:4]} ")

KNN Regressor Score is 0.63
KNN Regressor (CV) Score is 0.64
SVM Score is -0.0
SVM Regressor (CV) Score is -0.0
DTC Score is 0.00
Decision Tree Regressor (CV) Score is 0.61
RFC Score is 0.00
Random Forest Regressor Score is 0.89

## 6. Generate Submission File

Choose the model that has the best performance to generate a submission file.

In [81]:

cols_to_drop_test = df.isnull().sum()[df.isnull().sum() > 1000].index.tolist()
dt_cleaned = dt.drop(columns=cols_to_drop_test)

numerical_cols_for_imputation = ['LotFrontage', 'MasVnrArea', 'GarageYrBlt']
for col in numerical_cols_for_imputation:
    if col in dt_cleaned.columns:
        median_val_train = df_encoded[col].median()
        dt_cleaned[col].fillna(median_val_train, inplace=True)

categorical_cols_with_missing_test = dt_cleaned.select_dtypes(include='object').columns[dt_cleaned.select_dtypes(include='object').isnull().any()]
for col in categorical_cols_with_missing_test:
    if col in df_cleaned.columns:
        mode_val_train = df_cleaned[col].mode()[0]
        dt_cleaned[col].fillna(mode_val_train, inplace=True)
    else:
         dt_cleaned[col].fillna('Missing', inplace=True)

dt_encoded = pd.get_dummies(dt_cleaned, columns=dt_cleaned.select_dtypes(include='object').columns, dummy_na=False)

train_cols = X.columns
test_cols = dt_encoded.columns

missing_in_test = set(train_cols) - set(test_cols)
for c in missing_in_test:
    dt_encoded[c] = 0

extra_in_test = set(test_cols) - set(train_cols)
dt_encoded = dt_encoded.drop(columns=list(extra_in_test))

dt_encoded = dt_encoded[train_cols]

X_test_submission = dt_encoded
y_pred_submission = rfr.predict(X_test_submission)
submission_ids = dt['Id']

submission_df = pd.DataFrame({
    'Id': submission_ids,
    'SalePrice': y_pred_submission
})

submission_df.to_csv('submission_file.csv', index=False)

print("Submission file created successfully: submission_file.csv")
display(submission_df.head())

Submission file created successfully: submission_file.csv

     Id  SalePrice
0  1461  127615.32
1  1462  155716.00
2  1463  187960.00
3  1464  183487.00
4  1465  197479.00